# Render configuration for ETL Pipeline
services:
  - type: web
    name: etl-pipeline
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: UPLOAD_DIR
        value: "uploads"
      - key: PORT
        value: "8000"  # Use 8000 to match uvicorn default
      - key: DATABASE_URL
        value: ""  # Will be automatically populated by Render
    plan: free

databases:
  - type: postgresql
    name: etl-db
    databaseName: etl_db
    user: etl_user
    plan: free
